services:
  backend:
    build: .
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started
    ports:
      - '80:80'
    volumes:
      - .:/backend
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: shopper

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U root -d shopper']
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - shopper_db:/var/lib/postgresql/data
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: root1234
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    ports:
      - '9000:9000'
      - '9001:9001'
volumes:
  shopper_db:
  minio_data:
