services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: shopper
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U root -d shopper']
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - shopper_db:/var/lib/postgresql/data
    ports:
      - '5433:5432'
volumes:
  shopper_db:
